name: Build Windows
permissions:
  contents: read
on:
  workflow_dispatch:
  #push:
  #  branches:
  #pull_request:
  #  branches:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:

  build-windows:
    name: Build on Windows with Swift 6.2
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v4

      - name: Install Swift 6.2 silently
        shell: pwsh
        run: |
        - name: Install Visual Studio (build tools only)
          shell: pwsh
          run: |
            curl -LO https://aka.ms/vs/17/release/vs_buildtools.exe
            ./vs_buildtools.exe `
              --quiet `
              --wait `
              --norestart `
              --nocache `
              --installPath C:\BuildTools `
              --add Microsoft.VisualStudio.Component.Windows11SDK.22000 `
              --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 `
              --add Microsoft.VisualStudio.Component.VC.Tools.ARM64
            Invoke-WebRequest -Uri https://download.swift.org/swift-6.2-release/windows10/swift-6.2-RELEASE/swift-6.2-RELEASE-windows10.exe `
              -OutFile swift-installer.exe
            Start-Process -FilePath .\swift-installer.exe -ArgumentList "/quiet" -Wait
            # , "/verysilent", "/InstallAllUsers"
            $installPath = "C:\Program Files\Swift\bin"
            $env:Path += ";$installPath"
            [System.Environment]::SetEnvironmentVariable("PATH", $env:Path, [System.EnvironmentVariableTarget]::Process)
            #
            swift --version

      - name: Check Swift Version
        run: swift --version
