name: Generate and Push Swift Documentation

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clean docs folder
        run: rm -rf docs

      - name: Generate documentation
        run: |
        swift package \
          --allow-writing-to-directory ./docs \
          generate-documentation \
          --target RabFoundation \
          --output-path ./docs \
          --transform-for-static-hosting \
          --hosting-base-path RABFoundation

      - name: Clone wiki repo
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone https://x-access-token:${TOKEN}@github.com/auvents-brave/RabFoundation.wiki.git wiki

      - name: Copy generated docs to wiki
        run: |
          rm -rf wiki/docs
          mkdir -p wiki/docs
          cp -r docs/* wiki/docs/

      - name: Commit and push docs to wiki
        run: |
          cd wiki
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "Update Swift documentation" || echo "No changes to commit"
          git push
